config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :products
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  include ImageUploader::Attachment.new(:image)

  belongs_to :imageable, polymorphic: true, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader[:image]

  validates :content, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    p = Product.find(@image.imageable_id)
    @image.destroy
    respond_to do |format|
      format.html { redirect_to edit_product_path(p), notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:images).permit(:image, :description, :image_data, :imageable_id, :imageable_type, :remove_image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @image = @product.images.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, images_attributes: [:image, :description, :image_data, :imageable_id, :imageable_type, :remove_image])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association, options={})
    new_object = f.object.class.reflect_on_association(association).klass.new

    fields = f.fields_for(association,
        new_object,
        :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    link_to_function(name,
      h("add_fields(this,
        \"#{association}\", \"#{escape_javascript(fields)}\"); return false;"), class: 'btn btn-success mb-2')
  end

  def link_to_function(name, js, opts={})
    link_to name, '#', opts.merge({onclick: js})
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :image_description %>
  </div>

  <div class="field">
    <%= form.label :image_data %>
    <%= form.text_area :image_data, id: :image_image_data %>
  </div>

  <div class="field">
    <%= form.label :imageable_id %>
    <%= form.text_field :imageable_id, id: :image_imageable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image data</th>
      <th>Imageable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.description %></td>
        <td><%= image.image_data %></td>
        <td><%= image.imageable %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>Image data:</strong>
  <%= @image.image_data %>
</p>

<p>
  <strong>Imageable:</strong>
  <%= @image.imageable %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShrineFileUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '//cdn.jsdelivr.net/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <% if post.image.present? %>
      <%= image_tag(post.image_url(:thumb)) %>
    <% end %>
    <%= form.label :image %>
    <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image, id: :post_image_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.image_data %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image data:</strong>
  <% if @post.image.present? %>
    <%= image_tag @post.image_url(:original) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Product Name' %>
    <%= form.text_field :name, id: :product_name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.fields_for :images do |image_form| %>
      <%= render 'image_fields', f: image_form %>
    <% end %>
  </div>

  <%= link_to_add_fields "Add Image", form, :images, {class: 'btn btn-default'} %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_image_fields.html.erb
<div class="fields mt-1 p-2 jumbotron">

  <div class="form-group">
    <%= f.label :description, 'Image Description' %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :image, value: f.object.cached_image_data %>
    <%= f.file_field :image, id: :image_image_data %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", '#', onClick: "removeField(this); return false;", class: 'btn btn-sm btn-danger' %>
  </div>

  <div class="form-group">
    <% if f.object.image.present? %>
      <%= image_tag(f.object.image_url) %>
    <% end %>
  </div>



</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_with(model: @product, local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Product Name' %>
    <%= form.text_field :name, id: :product_name, class: 'form-control' %>
  </div>

  <div class="jumbotron">
    <% @product.images.each do |i| %>
      <p><%= image_tag i.image_url(:thumb) %></p>
      <p><%= link_to 'Delete', image_path(i), method: :delete %></p>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="row">
  <div class="col-12">
    <h1>New Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Images:</strong>
  <% @product.images.each do |img| %>
    <p><%= img.description %></p>
    <% if img.image.present? %>
      <p>Original</p>
      <%= image_tag img.image_url(:original) %>
      <p>Thumb</p>
      <%= image_tag img.image_url(:thumb) %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>